// SmartlogiV2_FrontEnd/src/app/Modules/Dashboard/livreur-dashboard/livreur-dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NotificationService } from '../../../Core/services/notification.service';
import { ColisService } from '../../../Core/services/colis.service';
import { AuthService } from '../../../Core/services/auth.service';
import { LivreurService } from '../../../Core/services/livreur.service';

import { Router } from '@angular/router';

import { FormsModule } from '@angular/forms'; // Add Import

@Component({
    selector: 'app-livreur-dashboard',
    standalone: true,
    imports: [CommonModule, FormsModule], // Add FormsModule
    templateUrl: './livreur-dashboard.component.html',
    styleUrl: './livreur-dashboard.component.css'
})
export class LivreurDashboardComponent implements OnInit {
    notifications: any[] = [];
    assignedColis: any[] = [];
    livreurId: string = '';
    isLoading = false;
    isNotificationsModalOpen = false;

    // UI State
    currentFilter: 'ALL' | 'TO_COLLECT' | 'TO_DELIVER' | 'HISTORY' = 'ALL';

    constructor(
        private notificationService: NotificationService,
        private livreurService: LivreurService,
        private authService: AuthService,
        private colisService: ColisService,
        private router: Router
    ) { }

    // --- Computed Properties ---

    get currentDate(): Date {
        return new Date();
    }

    get stats() {
        return {
            total: this.assignedColis.length,
            toCollect: this.assignedColis.filter(c => c.status === 'COLLECTE' || c.status === 'CREE').length,
            toDeliver: this.assignedColis.filter(c => c.status === 'EN_TRANSIT' || c.status === 'EN_STOCK').length,
            completed: this.assignedColis.filter(c => c.status === 'LIVRE').length
        };
    }

    get filteredColis() {
        switch (this.currentFilter) {
            case 'TO_COLLECT':
                return this.assignedColis.filter(c => c.status === 'COLLECTE' || c.status === 'CREE');
            case 'TO_DELIVER':
                return this.assignedColis.filter(c => c.status === 'EN_TRANSIT' || c.status === 'EN_STOCK');
            case 'HISTORY':
                return this.assignedColis.filter(c => c.status === 'LIVRE' || c.status === 'ANNULE');
            default:
                return this.assignedColis; // ALL includes active only? or everything? adjusting to show active by default if needed, but ALL is fine.
        }
    }

    // --- Actions ---

    setFilter(filter: 'ALL' | 'TO_COLLECT' | 'TO_DELIVER' | 'HISTORY') {
        this.currentFilter = filter;
    }

    openNotificationsModal() {
        this.isNotificationsModalOpen = true;
    }

    closeNotificationsModal() {
        this.isNotificationsModalOpen = false;
    }

    toggleNotificationsModal() {
        this.isNotificationsModalOpen = !this.isNotificationsModalOpen;
    }

    logout() {
        this.authService.logout();
        this.router.navigate(['/login']);
    }

    ngOnInit(): void {
        const token = this.authService.token;
        if (token) {
            this.livreurId = this.extractUserId(token);
            this.loadNotifications();
            this.loadAssignedColis();
        }
    }

    private extractUserId(token: string): string {
        try {
            const payload = JSON.parse(atob(token.split('.')[1]));
            return payload.userId || payload.sub;
        } catch (e) {
            console.error('Error decoding token', e);
            return '';
        }
    }

    loadNotifications() {
        this.notificationService.getMyNotifications().subscribe({
            next: (data) => this.notifications = data,
            error: (err) => console.error('Error loading notifications', err)
        });
    }

    loadAssignedColis() {
        if (!this.livreurId) return;
        this.isLoading = true;
        this.colisService.getMyAssignedColis(0, 100).subscribe({
            next: (data) => {
                this.assignedColis = data.content || [];
                // Sort by date desc
                this.assignedColis.sort((a, b) => new Date(b.dateCreation).getTime() - new Date(a.dateCreation).getTime());
                this.isLoading = false;
            },
            error: (err) => {
                console.error('Error loading assigned colis', err);
                this.isLoading = false;
            }
        });
    }

    markAsRead(id: string) {
        this.notificationService.markAsRead(id).subscribe({
            next: () => {
                this.notifications = this.notifications.map(n => n.id === id ? { ...n, read: true } : n);
            }
        });
    }

    updateStatusColis(colis: any, newStatus: string) {
        if (!confirm(`Confirmer le changement de statut vers ${newStatus} ?`)) return;

        this.colisService.updateStatus(colis.id, newStatus).subscribe({
            next: (updated) => {
                this.loadAssignedColis(); // Reload list
            },
            error: (err) => console.error('Error updating status', err)
        });
    }

    getAvailableStatuses(currentStatus: string): string[] {
        if (currentStatus === 'COLLECTE') return ['EN_STOCK'];
        // EN_STOCK is now handled by Manager assignment to switch to EN_TRANSIT, but we keep it empty as per requirement
        if (currentStatus === 'EN_STOCK') return [];
        if (currentStatus === 'EN_TRANSIT') return ['LIVRE', 'ANNULE', 'EN_STOCK'];
        return [];
    }

    getStatusColor(status: string): string {
        switch (status) {
            case 'CREE': return 'text-yellow-400 bg-yellow-400/10 border-yellow-400/20';
            case 'COLLECTE': return 'text-blue-400 bg-blue-400/10 border-blue-400/20';
            case 'EN_STOCK': return 'text-slate-300 bg-slate-500/10 border-slate-500/20';
            case 'EN_TRANSIT': return 'text-purple-400 bg-purple-400/10 border-purple-400/20';
            case 'LIVRE': return 'text-green-400 bg-green-400/10 border-green-400/20';
            case 'ANNULE': return 'text-red-400 bg-red-400/10 border-red-400/20';
            default: return 'text-slate-400 bg-slate-400/10 border-slate-400/20';
        }
    }
}

<div class="flex h-screen overflow-hidden bg-[#020617] text-white font-sans selection:bg-cyan-500/30 selection:text-cyan-200">

    <!-- Sidebar (Desktop) -->
    <aside class="hidden md:flex w-72 flex-col bg-[#050b14] border-r border-white/5 relative z-20">
        <!-- Logo Area -->
        <div class="p-8 pb-4">
            <h1 class="text-3xl font-black tracking-tighter text-transparent bg-clip-text bg-gradient-to-r from-white to-slate-400">
                SMART<span class="text-cyan-500">LOGI</span>
            </h1>
            <p class="text-slate-500 text-xs mt-2 uppercase tracking-widest font-bold px-0.5">Delivery Agent Portal</p>
        </div>

        <!-- Navigation -->
        <nav class="flex-1 px-4 space-y-1 mt-8">
            <button (click)="setFilter('ALL')" 
                    [class.bg-cyan-500_10]="currentFilter === 'ALL'"
                    [class.text-cyan-400]="currentFilter === 'ALL'"
                    class="w-full flex items-center gap-3 px-4 py-3.5 rounded-xl text-sm font-bold text-slate-400 hover:text-white hover:bg-white/5 transition-all group">
                <svg class="w-5 h-5 transition-colors" [class.text-cyan-500]="currentFilter === 'ALL'" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z"/></svg>
                Dashboard
            </button>
            <button (click)="setFilter('TO_COLLECT')"
                    [class.bg-cyan-500_10]="currentFilter === 'TO_COLLECT'"
                    [class.text-cyan-400]="currentFilter === 'TO_COLLECT'"
                    class="w-full flex items-center gap-3 px-4 py-3.5 rounded-xl text-sm font-bold text-slate-400 hover:text-white hover:bg-white/5 transition-all group">
                <svg class="w-5 h-5 transition-colors" [class.text-cyan-500]="currentFilter === 'TO_COLLECT'" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4"/></svg>
                To Collect
                <span *ngIf="stats.toCollect > 0" class="ml-auto bg-cyan-500 text-black text-[10px] font-black px-2 py-0.5 rounded-full">{{ stats.toCollect }}</span>
            </button>
            <button (click)="setFilter('TO_DELIVER')"
                    [class.bg-cyan-500_10]="currentFilter === 'TO_DELIVER'"
                    [class.text-cyan-400]="currentFilter === 'TO_DELIVER'"
                     class="w-full flex items-center gap-3 px-4 py-3.5 rounded-xl text-sm font-bold text-slate-400 hover:text-white hover:bg-white/5 transition-all group">
                <svg class="w-5 h-5 transition-colors" [class.text-cyan-500]="currentFilter === 'TO_DELIVER'" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
                Active Deliveries
                <span *ngIf="stats.toDeliver > 0" class="ml-auto bg-purple-500 text-white text-[10px] font-black px-2 py-0.5 rounded-full">{{ stats.toDeliver }}</span>
            </button>
            <button (click)="setFilter('HISTORY')"
                    [class.bg-cyan-500_10]="currentFilter === 'HISTORY'"
                    [class.text-cyan-400]="currentFilter === 'HISTORY'"
                    class="w-full flex items-center gap-3 px-4 py-3.5 rounded-xl text-sm font-bold text-slate-400 hover:text-white hover:bg-white/5 transition-all group">
                <svg class="w-5 h-5 transition-colors" [class.text-cyan-500]="currentFilter === 'HISTORY'" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
                History
            </button>
        </nav>

        <!-- Bottom Actions -->
        <div class="px-4 pb-6 space-y-2">
            <button class="w-full flex items-center gap-3 px-4 py-3 rounded-xl hover:bg-white/5 text-slate-400 hover:text-white transition-all group">
                <div class="w-8 h-8 rounded-full bg-white/10 flex items-center justify-center text-white group-hover:bg-cyan-500 group-hover:text-black transition-colors">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"/></svg>
                </div>
                <div class="text-left">
                    <span class="block font-bold text-xs">My Profile</span>
                    <span class="block text-[10px] text-slate-500">ID: {{ livreurId.substring(0,8) }}</span>
                </div>
            </button>
            <button (click)="logout()" class="w-full flex items-center gap-3 px-4 py-3 rounded-xl hover:bg-red-500/10 text-slate-400 hover:text-red-500 transition-all group">
                <div class="w-8 h-8 rounded-full bg-white/10 flex items-center justify-center text-white group-hover:bg-red-500 group-hover:text-white transition-colors">
                   <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"/></svg>
                </div>
                 <span class="font-bold text-xs">Logout</span>
            </button>
        </div>
    </aside>


    <!-- Main Content Area -->
    <main class="flex-1 overflow-y-auto relative scroll-smooth">
        <!-- Background Gradient -->
        <div class="absolute top-0 left-0 w-full h-96 bg-gradient-to-b from-cyan-900/10 to-transparent pointer-events-none z-0"></div>

        <div class="p-6 md:p-10 relative z-10 max-w-7xl mx-auto">
            
            <!-- Header -->
            <header class="flex flex-col md:flex-row md:items-center justify-between mb-10 gap-6">
                <div>
                     <p class="text-slate-400 font-bold uppercase text-xs tracking-widest mb-1">{{ currentDate | date:'fullDate' }}</p>
                     <h2 class="text-3xl md:text-4xl font-black text-white">Welcome back!</h2>
                     <p class="text-slate-500 mt-2">Here's your delivery manifest for today.</p>
                </div>
                
                <div class="flex items-center gap-4">
                    <!-- Notification Bell -->
                    <button (click)="toggleNotificationsModal()" class="relative w-12 h-12 rounded-xl bg-white/5 border border-white/10 hover:border-cyan-500/50 hover:bg-white/10 flex items-center justify-center transition-all group">
                         <svg class="w-6 h-6 text-slate-400 group-hover:text-white transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"/></svg>
                         <span *ngIf="notifications.length > 0" class="absolute top-2.5 right-3 w-2.5 h-2.5 bg-red-500 rounded-full border-2 border-[#050b14]"></span>
                    </button>
                    <!-- Mobile Menu Button (Optional, simple placeholder) -->
                    <button class="md:hidden w-12 h-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center">
                        <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/></svg>
                    </button>
                </div>
            </header>

            <!-- Stats Grid -->
            <div class="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
                <!-- Total Load -->
                <div class="bg-[#0f172a]/50 backdrop-blur border border-white/5 p-5 rounded-2xl relative overflow-hidden group">
                    <div class="absolute right-0 top-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                        <svg class="w-16 h-16 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"/></svg>
                    </div>
                    <p class="text-slate-400 text-xs font-bold uppercase tracking-wider mb-1">Assigned</p>
                    <p class="text-3xl font-black text-white">{{ stats.total }}</p>
                    <div class="mt-3 text-xs text-slate-500 font-medium">Total parcels</div>
                </div>

                <!-- To Collect -->
                <div class="bg-[#0f172a]/50 backdrop-blur border border-white/5 p-5 rounded-2xl relative overflow-hidden group">
                     <div class="absolute right-0 top-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                        <svg class="w-16 h-16 text-cyan-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4"/></svg>
                    </div>
                    <p class="text-cyan-500/80 text-xs font-bold uppercase tracking-wider mb-1">Pickup</p>
                    <p class="text-3xl font-black text-cyan-400">{{ stats.toCollect }}</p>
                    <div class="mt-3 text-xs text-cyan-500/50 font-medium">Pending collection</div>
                </div>

                 <!-- To Deliver -->
                 <div class="bg-[#0f172a]/50 backdrop-blur border border-white/5 p-5 rounded-2xl relative overflow-hidden group">
                    <div class="absolute right-0 top-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                       <svg class="w-16 h-16 text-purple-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
                   </div>
                   <p class="text-purple-500/80 text-xs font-bold uppercase tracking-wider mb-1">Transit</p>
                   <p class="text-3xl font-black text-purple-400">{{ stats.toDeliver }}</p>
                   <div class="mt-3 text-xs text-purple-500/50 font-medium">En route</div>
               </div>

                <!-- Completed -->
                <div class="bg-[#0f172a]/50 backdrop-blur border border-white/5 p-5 rounded-2xl relative overflow-hidden group">
                    <div class="absolute right-0 top-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                       <svg class="w-16 h-16 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
                   </div>
                   <p class="text-green-500/80 text-xs font-bold uppercase tracking-wider mb-1">Delivered</p>
                   <p class="text-3xl font-black text-green-400">{{ stats.completed }}</p>
                   <div class="mt-3 text-xs text-green-500/50 font-medium">Successfully delivered</div>
               </div>
            </div>

            <!-- Content Area: Parcels -->
            <div>
                 <div class="flex items-center justify-between mb-6">
                    <h3 class="text-xl font-bold flex items-center gap-2">
                        <span class="w-2 h-8 bg-cyan-500 rounded-full"></span>
                        {{ currentFilter === 'ALL' ? 'All Parcels' : (currentFilter === 'TO_COLLECT' ? 'Pending Collection' : (currentFilter === 'TO_DELIVER' ? 'Active Deliveries' : 'History')) }}
                    </h3>
                 </div>

                <!-- Loading -->
                <div *ngIf="isLoading" class="flex justify-center py-20">
                    <div class="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-cyan-500"></div>
                </div>

                <!-- Empty State -->
                <div *ngIf="!isLoading && filteredColis.length === 0" class="text-center py-20 border border-dashed border-white/10 rounded-2xl text-slate-500">
                    <svg class="w-16 h-16 mx-auto mb-4 opacity-50" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4"/></svg>
                    Nothing to show here yet.
                </div>

                <!-- Grid -->
                <!-- Grid -->
                 <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    <div *ngFor="let colis of filteredColis" class="bg-[#0f172a] border border-white/5 rounded-2xl overflow-hidden relative group hover:border-cyan-500/30 transition-all flex flex-col">
                        
                        <!-- Card Header -->
                        <div class="p-6 pb-4">
                            <div class="flex justify-between items-start mb-4">
                                <span [ngClass]="getStatusColor(colis.status)" class="text-[10px] font-black px-2 py-1 rounded-lg uppercase tracking-wider border">
                                    {{ colis.status }}
                                </span>
                                <span class="bg-white/5 text-slate-500 text-[10px] font-mono px-2 py-1 rounded border border-white/5">
                                    #{{ colis.id.substring(0,8) }}
                                </span>
                            </div>
                            
                            <h3 class="text-white font-bold text-lg leading-tight mb-2">{{ colis.villeDestination }}</h3>
                            <p class="text-slate-400 text-sm line-clamp-2 min-h-[2.5rem]">{{ colis.description || 'No additional details provided.' }}</p>
                        </div>

                        <!-- Card Meta -->
                        <div class="px-6 py-3 border-t border-white/5 bg-black/20 mt-auto">
                            <div class="flex justify-between items-center text-xs">
                                <span class="font-bold flex items-center gap-2" [ngClass]="{'text-red-400': colis.prioriteStatus === 'URGENT', 'text-blue-400': colis.prioriteStatus === 'NORMAL', 'text-slate-400': colis.prioriteStatus === 'FAIBLE'}">
                                     <span class="w-1.5 h-1.5 rounded-full bg-current"></span>
                                     {{ colis.prioriteStatus }}
                                </span>
                                <span class="text-slate-500">{{ colis.dateCreation | date:'MMM d, h:mm a' }}</span>
                            </div>
                        </div>

                        <!-- Card Actions -->
                        <div class="p-4 pt-2 bg-black/40 border-t border-white/5 grid grid-cols-2 gap-2" *ngIf="getAvailableStatuses(colis.status).length > 0">
                             <button *ngFor="let status of getAvailableStatuses(colis.status)"
                                     (click)="updateStatusColis(colis, status)"
                                     [ngClass]="{
                                        'bg-purple-600 hover:bg-purple-500': status === 'EN_TRANSIT',
                                        'bg-green-600 hover:bg-green-500': status === 'LIVRE',
                                        'bg-red-600 hover:bg-red-500': status === 'ANNULE',
                                        'bg-slate-700 hover:bg-slate-600': status === 'EN_STOCK'
                                     }"
                                     class="col-span-1 text-white text-[10px] font-bold py-2.5 px-3 rounded-lg transition-all uppercase tracking-wide flex items-center justify-center gap-1">
                                 {{ status.replace('_', ' ') }}
                             </button>
                        </div>
                        <div class="p-4 pt-2 bg-black/40 border-t border-white/5 text-center" *ngIf="getAvailableStatuses(colis.status).length === 0">
                            <span class="text-[10px] text-slate-500 font-medium italic">No actions available</span>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </main>

    <!-- Notifications Modal -->
    <div *ngIf="isNotificationsModalOpen" class="fixed inset-0 bg-black/90 backdrop-blur-md z-50 flex items-center justify-center p-4" (click)="closeNotificationsModal()">
        <div class="bg-[#0f172a] border border-white/10 rounded-3xl w-full max-w-lg max-h-[85vh] flex flex-col shadow-2xl relative overflow-hidden" (click)="$event.stopPropagation()">
            <!-- Modal Header -->
            <div class="p-6 border-b border-white/10 flex justify-between items-center bg-[#0f172a] z-10 sticky top-0">
                <h3 class="text-xl font-bold text-white flex items-center gap-2">
                    <span class="w-8 h-8 rounded-lg bg-yellow-500/20 text-yellow-500 flex items-center justify-center">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"/></svg>
                    </span>
                    Notifications
                </h3>
                <button (click)="closeNotificationsModal()" class="w-8 h-8 rounded-full hover:bg-white/10 flex items-center justify-center transition-colors text-slate-400 hover:text-white">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg>
                </button>
            </div>

            <!-- Modal Body -->
            <div class="p-0 overflow-y-auto">
                <div *ngFor="let notif of notifications" 
                     [class.bg-white_5]="!notif.read"
                     class="p-5 border-b border-white/5 hover:bg-white/5 transition-colors group">
                    <div class="flex justify-between items-start gap-4">
                        <div class="flex-1">
                            <p class="text-sm text-slate-300 leading-relaxed font-medium" [class.text-white]="!notif.read">{{ notif.message }}</p>
                            <span class="text-[10px] text-slate-500 mt-2 block font-mono">{{ notif.dateCreation | date:'medium' }}</span>
                        </div>
                        <button *ngIf="!notif.read" (click)="$event.stopPropagation(); markAsRead(notif.id)" title="Mark as read" class="text-cyan-500 hover:text-cyan-400 opacity-0 group-hover:opacity-100 transition-opacity">
                            <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"/></svg>
                        </button>
                    </div>
                </div>
                
                <div *ngIf="notifications.length === 0" class="flex flex-col items-center justify-center py-20 text-slate-500">
                     <svg class="w-12 h-12 mb-3 opacity-30" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4"/></svg>
                    <p>No notifications yet</p>
                </div>
            </div>
        </div>
    </div>

</div>

// SmartlogiV2_FrontReactTs/src/features/dashboard/pages/LivreurDashboard.tsx
import React, { useState, useEffect } from 'react';
import { useAppDispatch, useAppSelector } from '../../../store/hooks';
import { selectUser, logout } from '../../auth/authSlice';
import { useNavigate } from 'react-router-dom';
import UserProfile from '../../users/components/UserProfile';
import { fetchMissions, updateMission, fetchNotifications, markRead } from '../livreurSlice';

const LivreurDashboard = () => {
    const dispatch = useAppDispatch();
    const navigate = useNavigate();
    const user = useAppSelector(selectUser);
    const { missions, notifications, loading } = useAppSelector(state => state.livreur);
    
    // Local State
    const [activeTab, setActiveTab] = useState<'MISSIONS' | 'HISTORY' | 'PROFILE' | 'NOTIFICATIONS'>('MISSIONS');
    
    // Mission Filtering
    // Active missions are those not delivered or cancelled
    const activeMissions = missions.filter(m => m.statut !== 'LIVRE' && m.statut !== 'ANNULE');
    const historyMissions = missions.filter(m => m.statut === 'LIVRE' || m.statut === 'ANNULE');

    useEffect(() => {
        dispatch(fetchMissions());
        dispatch(fetchNotifications());
    }, [dispatch]);

    const handleLogout = () => {
        dispatch(logout());
        navigate('/staff-login');
    };

    const handleStatusUpdate = async (id: string, currentStatus: string) => {
        let nextStatus = '';
        if (currentStatus === 'CREE') nextStatus = 'COLLECTE';
        else if (currentStatus === 'COLLECTE') nextStatus = 'EN_TRANSIT';
        else if (currentStatus === 'EN_TRANSIT') nextStatus = 'LIVRE';
        
        if (nextStatus) {
            await dispatch(updateMission({ id, status: nextStatus, comment: 'Status updated by driver' }));
        }
    };

    const handleMarkRead = (id: string) => {
        dispatch(markRead(id));
    };

    const unreadCount = notifications.filter(n => !n.read).length;

    return (
        <div className="min-h-screen bg-stone-50 text-slate-900 font-sans selection:bg-orange-100 selection:text-orange-900">
            {/* Top Navigation Bar */}
            <nav className="sticky top-0 z-50 bg-slate-900 shadow-xl shadow-slate-900/10">
                <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
                    {/* Logo Area */}
                    <div className="flex items-center gap-2">
                         <div className="w-8 h-8 bg-orange-500 rounded-lg flex items-center justify-center font-black text-white text-lg">S</div>
                         <span className="font-bold text-lg tracking-tight text-white">SmartLogi<span className="text-orange-500">Driver</span></span>
                    </div>

                    {/* Tabs */}
                    <div className="flex bg-slate-800/50 p-1 rounded-xl border border-white/5">
                        <button onClick={() => setActiveTab('MISSIONS')} className={`px-4 py-1.5 rounded-lg text-xs font-bold uppercase tracking-wide transition-all ${activeTab === 'MISSIONS' ? 'bg-orange-500 text-white shadow-lg shadow-orange-500/20' : 'text-slate-400 hover:bg-slate-800 hover:text-white'}`}>
                            Missions ({activeMissions.length})
                        </button>
                        <button onClick={() => setActiveTab('HISTORY')} className={`px-4 py-1.5 rounded-lg text-xs font-bold uppercase tracking-wide transition-all ${activeTab === 'HISTORY' ? 'bg-orange-500 text-white shadow-lg shadow-orange-500/20' : 'text-slate-400 hover:bg-slate-800 hover:text-white'}`}>
                            History
                        </button>
                    </div>

                    {/* Profile & Notifs */}
                    <div className="flex items-center gap-5">
                        {/* Notification Bell */}
                        <div className="relative cursor-pointer group" onClick={() => setActiveTab('NOTIFICATIONS')}>
                            <div className={`p-2 rounded-full transition-colors ${activeTab === 'NOTIFICATIONS' ? 'bg-slate-800 text-orange-500' : 'text-slate-400 group-hover:text-white group-hover:bg-slate-800'}`}>
                                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"></path></svg>
                            </div>
                            {unreadCount > 0 && (
                                <span className="absolute top-1 right-1 w-2.5 h-2.5 bg-red-500 rounded-full border-2 border-slate-900"></span>
                            )}
                        </div>

                        {/* Profile Trigger */}
                        <div className="cursor-pointer" onClick={() => setActiveTab('PROFILE')}>
                            <div className="w-9 h-9 rounded-full bg-gradient-to-tr from-orange-600 to-orange-400 p-[2px]">
                                <div className="w-full h-full rounded-full bg-slate-900 flex items-center justify-center text-white font-bold text-xs uppercase hover:bg-slate-800 transition">
                                    {user?.prenom?.charAt(0) || 'U'}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>

            {/* Main Content */}
            <main className="max-w-3xl mx-auto px-4 py-8">
                {activeTab === 'MISSIONS' && (
                    <div className="space-y-6 animate-fadeIn">
                        <div className="flex justify-between items-end mb-2">
                             <div>
                                 <h2 className="text-2xl font-black text-slate-900">Active Missions</h2>
                                 <p className="text-slate-500 font-medium text-sm">Manage your current pickups and deliveries.</p>
                             </div>
                             <button onClick={() => dispatch(fetchMissions())} className="bg-white hover:bg-orange-50 text-slate-400 hover:text-orange-600 p-2.5 rounded-xl border border-stone-200 shadow-sm transition-all">
                                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"></path></svg>
                             </button>
                        </div>
                        
                        {loading && (
                            <div className="flex justify-center py-12">
                                <div className="w-8 h-8 border-4 border-orange-200 border-t-orange-500 rounded-full animate-spin"></div>
                            </div>
                        )}
                        
                        {!loading && activeMissions.length === 0 && (
                            <div className="bg-white p-12 rounded-3xl shadow-sm border border-stone-100 text-center">
                                <div className="w-20 h-20 bg-stone-50 rounded-full flex items-center justify-center mx-auto mb-6 text-stone-300">
                                    <svg className="w-10 h-10" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                                </div>
                                <h3 className="text-xl font-bold text-slate-900 mb-2">All Caught Up!</h3>
                                <p className="text-slate-500 max-w-xs mx-auto">You have no active missions at the moment. Enjoy the break or check back later.</p>
                            </div>
                        )}

                        {activeMissions.map(mission => (
                            <div key={mission.id} className="bg-white rounded-3xl shadow-xl shadow-stone-200/50 border border-white overflow-hidden group hover:border-orange-200 transition-all duration-300">
                                <div className="p-6">
                                    <div className="flex justify-between items-start mb-6">
                                        <div className="flex items-start gap-4">
                                            <div className={`w-12 h-12 rounded-2xl flex items-center justify-center text-xl shadow-inner ${
                                                mission.statut === 'CREE' ? 'bg-blue-50 text-blue-600' :
                                                mission.statut === 'COLLECTE' ? 'bg-orange-50 text-orange-600' :
                                                'bg-purple-50 text-purple-600'
                                            }`}>
                                                {mission.statut === 'CREE' ? '📦' : mission.statut === 'COLLECTE' ? '🚚' : '🏁'}
                                            </div>
                                            <div>
                                                <div className="flex items-center gap-2 mb-1">
                                                    <span className={`px-2.5 py-1 rounded-lg text-[10px] font-black uppercase tracking-widest ${
                                                        mission.statut === 'CREE' ? 'bg-blue-100/50 text-blue-700' :
                                                        mission.statut === 'COLLECTE' ? 'bg-orange-100/50 text-orange-700' :
                                                        'bg-purple-100/50 text-purple-700'
                                                    }`}>
                                                        {mission.statut}
                                                    </span>
                                                    <span className="text-xs text-stone-400 font-bold tracking-wider">#{mission.id.substring(0,8)}</span>
                                                </div>
                                                <h3 className="font-bold text-lg text-slate-900">
                                                    {mission.statut === 'CREE' ? 'Pickup Request' : 'Delivery Mission'}
                                                </h3>
                                                <p className="text-sm text-slate-500 font-medium">To: {mission.villeDestination}</p>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div className="bg-stone-50 rounded-2xl p-5 mb-6 border border-stone-100">
                                        <div className="flex gap-4">
                                            <div className="flex flex-col items-center pt-1">
                                                <div className="w-2.5 h-2.5 rounded-full bg-slate-300"></div>
                                                <div className="w-0.5 h-full bg-slate-200 my-1"></div>
                                                <div className="w-2.5 h-2.5 rounded-full border-2 border-orange-500 bg-white"></div>
                                            </div>
                                            <div className="flex-1 space-y-6">
                                                <div>
                                                    <div className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">From (Origin)</div>
                                                    <div className="font-bold text-slate-800">{mission.expediteur?.nom || 'Warehouse'}</div>
                                                    <div className="text-sm text-slate-500">{mission.codePostalOrigine} {mission.zoneOrigine?.nom}</div>
                                                </div>
                                                <div>
                                                    <div className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">To (Destination)</div>
                                                    <div className="font-bold text-slate-800">{mission.destinataire?.nom}</div>
                                                    <div className="text-sm text-slate-500">{mission.destinataire?.adresse}</div>
                                                    <div className="text-sm text-orange-600 font-bold">{mission.villeDestination}</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Actions */}
                                    <div className="grid grid-cols-1 gap-3">
                                        {mission.statut === 'CREE' && (
                                            <button 
                                                onClick={() => handleStatusUpdate(mission.id, 'CREE')}
                                                className="w-full bg-slate-900 hover:bg-slate-800 text-white py-3.5 rounded-2xl font-bold text-sm shadow-xl shadow-slate-900/20 transition-all flex items-center justify-center gap-2 group-hover:scale-[1.02]"
                                            >
                                                <span>Validate Pickup</span>
                                                <svg className="w-4 h-4 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M14 5l7 7m0 0l-7 7m7-7H3"></path></svg>
                                            </button>
                                        )}
                                        {mission.statut === 'COLLECTE' && (
                                             <button 
                                                onClick={() => handleStatusUpdate(mission.id, 'COLLECTE')}
                                                className="w-full bg-orange-600 hover:bg-orange-500 text-white py-3.5 rounded-2xl font-bold text-sm shadow-xl shadow-orange-500/30 transition-all flex items-center justify-center gap-2 group-hover:scale-[1.02]"
                                            >
                                                <span>Start Transit</span>
                                                <svg className="w-4 h-4 text-orange-200" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>
                                            </button>
                                        )}
                                        {mission.statut === 'EN_TRANSIT' && (
                                             <button 
                                                onClick={() => handleStatusUpdate(mission.id, 'EN_TRANSIT')}
                                                className="w-full bg-green-600 hover:bg-green-500 text-white py-3.5 rounded-2xl font-bold text-sm shadow-xl shadow-green-600/30 transition-all flex items-center justify-center gap-2 group-hover:scale-[1.02]"
                                            >
                                                <span>Confirm Delivery</span>
                                                <svg className="w-4 h-4 text-green-200" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path></svg>
                                            </button>
                                        )}
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                )}
                
                {activeTab === 'HISTORY' && (
                    <div className="space-y-6 animate-fadeIn">
                        <div>
                            <h2 className="text-2xl font-black text-slate-900">Task History</h2>
                            <p className="text-slate-500 font-medium text-sm">Your completed missions timeline.</p>
                        </div>
                        
                         {historyMissions.length === 0 && (
                             <div className="text-center py-12 text-slate-400 bg-stone-50 rounded-3xl border border-stone-200 border-dashed">No history available yet.</div>
                         )}

                         <div className="relative border-l-2 border-stone-200 ml-4 space-y-8 pl-8 py-2">
                             {historyMissions.map(mission => (
                                 <div key={mission.id} className="relative group">
                                     <div className={`absolute -left-[41px] w-6 h-6 rounded-full border-4 border-stone-100 ${mission.statut === 'LIVRE' ? 'bg-green-500' : 'bg-red-500'}`}></div>
                                     <div className="bg-white p-5 rounded-2xl shadow-sm border border-stone-100 group-hover:shadow-md transition-all">
                                         <div className="flex justify-between items-start mb-2">
                                             <div>
                                                 <span className={`inline-block px-2 py-0.5 rounded text-[10px] font-black uppercase tracking-wider mb-1 ${mission.statut === 'LIVRE' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
                                                    {mission.statut}
                                                 </span>
                                                 <h4 className="font-bold text-slate-900">Delivery to {mission.villeDestination}</h4>
                                             </div>
                                             <span className="text-xs font-bold text-slate-400">{new Date(mission.dateCreation).toLocaleDateString()}</span>
                                         </div>
                                         <div className="text-sm text-slate-500">
                                             Recipient: <span className="font-medium text-slate-700">{mission.destinataire?.nom}</span>
                                         </div>
                                          <div className="text-xs text-stone-400 mt-2 font-mono">ID: {mission.id}</div>
                                     </div>
                                 </div>
                             ))}
                         </div>
                    </div>
                )}

                {activeTab === 'NOTIFICATIONS' && (
                    <div className="space-y-6 animate-fadeIn">
                        <div className="flex justify-between items-center bg-white p-4 rounded-2xl shadow-sm border border-stone-100">
                             <div>
                                 <h2 className="text-lg font-black text-slate-900">Notifications</h2>
                                 <div className="text-xs text-slate-500 font-bold uppercase tracking-wider">Stay Updated</div>
                             </div>
                             <button onClick={() => dispatch(fetchNotifications())} className="text-orange-600 bg-orange-50 hover:bg-orange-100 px-3 py-1.5 rounded-lg text-xs font-bold transition-colors">Refresh</button>
                        </div>
                         
                        {notifications.length === 0 && <div className="text-center text-slate-400 py-12">No new notifications.</div>}

                        {notifications.map(notif => (
                            <div 
                                key={notif.id} 
                                onClick={() => !notif.read && handleMarkRead(notif.id)}
                                className={`p-5 rounded-2xl border transition-all ${notif.read ? 'bg-white border-stone-100 text-slate-400' : 'bg-white border-orange-200 shadow-lg shadow-orange-500/5 cursor-pointer relative overflow-hidden'}`}
                            >
                                {!notif.read && <div className="absolute left-0 top-0 bottom-0 w-1 bg-orange-500"></div>}
                                <div className="flex justify-between items-start mb-2">
                                    <div className={`text-sm ${!notif.read ? 'font-bold text-slate-900' : 'font-medium'}`}>{notif.message}</div>
                                    {!notif.read && <span className="flex h-2 w-2 relative">
                                        <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-orange-400 opacity-75"></span>
                                        <span className="relative inline-flex rounded-full h-2 w-2 bg-orange-500"></span>
                                    </span>}
                                </div>
                                <div className="text-[10px] font-bold uppercase tracking-wider text-slate-300">
                                    {new Date(notif.dateEnvoi).toLocaleString()}
                                </div>
                            </div>
                        ))}
                    </div>
                )}

                 {activeTab === 'PROFILE' && (
                    <div className="animate-fadeIn">
                         <UserProfile user={user} onLogout={handleLogout} />
                    </div>
                )}
            </main>
        </div>
    );
};

export default LivreurDashboard;
