// SmartlogiV2_FrontEnd/src/app/Modules/Dashboard/manager-dashboard/manager-dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../../Core/services/auth.service';
import { ColisService } from '../../../Core/services/colis.service';
import { LivreurService } from '../../../Core/services/livreur.service';
import { ZoneService } from '../../../Core/services/zone.service';

@Component({
    selector: 'app-manager-dashboard',
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule],
    templateUrl: './manager-dashboard.component.html',
    styleUrl: './manager-dashboard.component.css'
})
export class ManagerDashboardComponent implements OnInit {
    // Tabs
    activeTab: 'shipments' | 'personnel' = 'shipments';

    // Colis Data
    colisList: any[] = [];
    selectedColis: any | null = null;
    eligibleLivreurs: any[] = [];

    // Livreur Data
    livreurList: any[] = [];
    zoneList: any[] = [];
    isLivreurModalOpen = false;
    livreurForm: FormGroup;

    // Loading States
    isLoading = false;
    isAssignmentLoading = false;
    isLivreurActionLoading = false;

    // Pagination
    currentPage = 0;
    pageSize = 10;
    totalPages = 0;

    constructor(
        private colisService: ColisService,
        private livreurService: LivreurService,
        private zoneService: ZoneService,
        private fb: FormBuilder,
        private authService: AuthService,
        private router: Router
    ) {
        this.livreurForm = this.fb.group({
            nom: ['', Validators.required],
            prenom: ['', Validators.required],
            email: ['', [Validators.required, Validators.email]],
            telephone: ['', Validators.required],
            password: ['', Validators.required],
            confirmPassword: ['', Validators.required],
            vehicule: ['', Validators.required],
            zoneAssigneeId: ['', Validators.required]
        });
    }

    logout() {
        this.authService.logout();
        this.router.navigate(['/login']);
    }

    ngOnInit(): void {
        this.loadColis();
        this.loadZones();
    }

    switchTab(tab: 'shipments' | 'personnel') {
        this.activeTab = tab;
        if (tab === 'shipments') {
            this.loadColis();
        } else {
            this.loadLivreurs();
        }
    }

    // --- Colis Logic ---
    // --- Colis Logic ---
    loadColis() {
        this.isLoading = true;
        // If we want to show 'Assigned' specifically, we might need a different endpoint or filter.
        // For 'shipments' tab, let's show 'Available' (unassigned) by default, 
        // but maybe we add a sub-tab or toggle for 'All'/'Assigned'.
        // For this step, I will stick to 'Available' as per previous instruction, 
        // BUT the user asked to "Afficher colis assigner".
        // So I'll fetch ALL colis instead of just available, OR add a toggle.
        // Let's change behavior: Load ALL colis, and let UI filter or show status.
        // actually, getAvailableColis only returns unassigned. 
        // getAllColis returns everything.

        this.colisService.getAllColis(this.currentPage, this.pageSize).subscribe({
            next: (response) => {
                this.colisList = response.content;
                this.totalPages = response.totalPages;
                this.isLoading = false;
            },
            error: (err) => {
                console.error('Error loading colis', err);
                this.isLoading = false;
            }
        });
    }

    onSelectColis(colis: any) {
        this.selectedColis = colis;
        this.eligibleLivreurs = [];
        this.isAssignmentLoading = true;

        // Convert status if needed, assuming backend returns 'CREE', 'COLLECTE', etc.
        // We allow assignment mainly if status is CREE or maybe COLLECTE unassigned?
        // Logic: fetch eligible livreurs
        this.colisService.getEligibleLivreurs(colis.id).subscribe({
            next: (livreurs) => {
                this.eligibleLivreurs = livreurs;
                this.isAssignmentLoading = false;
            },
            error: (err) => {
                console.error('Error loading livreurs', err);
                this.isAssignmentLoading = false;
            }
        });
    }

    assignLivreur(livreurId: string) {
        if (!this.selectedColis) return;
        if (!confirm('Assign this livreur to the colis?')) return;

        this.isAssignmentLoading = true;
        this.colisService.assignLivreur(this.selectedColis.id, livreurId).subscribe({
            next: () => {
                alert('Livreur assigned successfully');
                this.selectedColis = null; // Close modal/panel
                this.loadColis(); // Refresh list
                this.isAssignmentLoading = false;
            },
            error: (err) => {
                console.error('Error assigning livreur', err);
                alert('Failed to assign livreur: ' + (err.error?.message || 'Unknown error'));
                this.isAssignmentLoading = false;
            }
        });
    }

    closePanel() {
        this.selectedColis = null;
        this.eligibleLivreurs = [];
    }

    // --- Livreur Logic ---
    loadLivreurs() {
        this.isLoading = true;
        this.livreurService.getAllLivreurs(this.currentPage, this.pageSize).subscribe({
            next: (response) => {
                this.livreurList = response.content;
                this.isLoading = false;
            },
            error: (err) => {
                console.error('Error loading livreurs', err);
                this.isLoading = false;
            }
        });
    }

    loadZones() {
        this.zoneService.getAllZones().subscribe({
            next: (zones) => {
                this.zoneList = zones;
            },
            error: (err) => console.error('Error loading zones', err)
        });
    }

    openLivreurModal() {
        this.isLivreurModalOpen = true;
        this.livreurForm.reset();
    }

    closeLivreurModal() {
        this.isLivreurModalOpen = false;
    }

    submitLivreur() {
        if (this.livreurForm.invalid) return;

        this.isLivreurActionLoading = true;
        this.livreurService.createLivreur(this.livreurForm.value).subscribe({
            next: () => {
                alert('Livreur created successfully');
                this.closeLivreurModal();
                this.loadLivreurs();
                this.isLivreurActionLoading = false;
            },
            error: (err) => {
                console.error('Error creating livreur', err);
                alert('Failed to create livreur');
                this.isLivreurActionLoading = false;
            }
        });
    }

    deleteLivreur(id: string) {
        if (!confirm('Are you sure you want to delete this agent?')) return;

        this.isLivreurActionLoading = true;
        this.livreurService.deleteLivreur(id).subscribe({
            next: () => {
                this.loadLivreurs();
                this.isLivreurActionLoading = false;
            },
            error: (err) => {
                console.error('Error deleting livreur', err);
                alert('Failed to delete livreur (might be assigned to active shipments)');
                this.isLivreurActionLoading = false;
            }
        });
    }

    // --- Tracking Logic ---
    isTrackingModalOpen = false;
    trackingHistory: any[] = [];
    trackingColisId: string = '';

    trackColis(colis: any) {
        this.trackingColisId = colis.id;
        this.isTrackingModalOpen = true;
        this.trackingHistory = [];

        this.colisService.getColisHistory(colis.id).subscribe({
            next: (data: any) => {
                // Assuming data is Page or List. Endpoint returns Page<HistoriqueLivraisonResponse>
                this.trackingHistory = data.content ? data.content : data;
            },
            error: (err) => console.error('Error loading history', err)
        });
    }

    closeTrackingModal() {
        this.isTrackingModalOpen = false;
        this.trackingHistory = [];
    }

    // --- Helpers ---
    getPrioriteClass(priorite: string): string {
        switch (priorite) {
            case 'URGENT': return 'text-red-500 font-bold';
            case 'NORMAL': return 'text-blue-500';
            case 'FAIBLE': return 'text-slate-500';
            default: return 'text-white';
        }
    }

    getStatusClass(status: string): string {
        switch (status) {
            case 'CREE': return 'bg-yellow-500/20 text-yellow-500 border-yellow-500/50';
            case 'COLLECTE': return 'bg-blue-500/20 text-blue-500 border-blue-500/50';
            case 'EN_STOCK': return 'bg-white/20 text-white border-white/50';
            case 'EN_TRANSIT': return 'bg-purple-500/20 text-purple-500 border-purple-500/50';
            case 'LIVRE': return 'bg-green-500/20 text-green-500 border-green-500/50';
            case 'ANNULE': return 'bg-red-500/20 text-red-500 border-red-500/50';
            default: return 'bg-slate-500/20 text-slate-500 border-slate-500/50';
        }
    }
}

<div class="p-6 md:p-10 min-h-screen bg-slate-950 text-white relative overflow-hidden">
    
    <!-- Header -->
    <div class="mb-8 flex flex-col md:flex-row justify-between items-start md:items-center z-10 relative gap-4">
        <div>
            <h1 class="text-3xl font-black tracking-tighter">SMART<span class="text-cyan-500">LOGI</span></h1>
            <p class="text-slate-400 text-sm mt-1">Manager Dashboard</p>
        </div>

        <div class="flex items-center gap-4">
            <!-- Tab Navigation -->
            <div class="flex bg-white/5 p-1 rounded-xl border border-white/10">
                <button (click)="switchTab('shipments')" 
                        [class.bg-cyan-600]="activeTab === 'shipments'"
                        [class.text-white]="activeTab === 'shipments'"
                        class="px-6 py-2 rounded-lg text-sm font-bold transition-all text-slate-400 hover:text-white">
                    Shipments
                </button>
                <button (click)="switchTab('personnel')" 
                        [class.bg-cyan-600]="activeTab === 'personnel'"
                        [class.text-white]="activeTab === 'personnel'"
                        class="px-6 py-2 rounded-lg text-sm font-bold transition-all text-slate-400 hover:text-white">
                    Personnel
                </button>
            </div>

            <!-- User Actions -->
            <div class="flex items-center gap-2 pl-4 border-l border-white/10">
                <button title="Profile" class="w-10 h-10 rounded-full bg-white/5 hover:bg-white/10 border border-white/10 flex items-center justify-center text-slate-400 hover:text-white transition">
                     <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"/></svg>
                </button>
                <button (click)="logout()" title="Logout" class="w-10 h-10 rounded-full bg-red-500/10 hover:bg-red-500/20 border border-red-500/20 flex items-center justify-center text-red-500 transition">
                     <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"/></svg>
                </button>
            </div>
        </div>
    </div>

    <!-- SHIPMENTS VIEW -->
    <div *ngIf="activeTab === 'shipments'" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6 z-10 relative">
        
        <!-- Loading State -->
        <div *ngIf="isLoading" class="col-span-full flex justify-center py-20">
            <div class="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-cyan-500"></div>
        </div>

        <!-- Colis Card -->
        <div *ngFor="let colis of colisList" 
             (click)="onSelectColis(colis)"
             class="group relative bg-[#0f172a] border border-white/5 rounded-2xl p-6 hover:border-cyan-500/50 hover:bg-[#0f172a]/80 transition-all duration-300 cursor-pointer overflow-hidden">
            
            <div class="absolute inset-0 bg-cyan-500/5 opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>

            <div class="relative z-10 space-y-4">
                <div class="flex justify-between items-start">
                    <span class="bg-white/5 text-slate-400 text-[10px] font-mono px-2 py-1 rounded border border-white/10">{{ colis.id.substring(0,8) }}...</span>
                    <span [ngClass]="getStatusClass(colis.status)" class="text-[10px] font-bold px-2 py-1 rounded border">
                        {{ colis.status }}
                    </span>
                </div>

                <div>
                    <h3 class="text-white font-bold text-lg leading-tight">{{ colis.villeDestination }}</h3>
                    <p class="text-slate-500 text-xs mt-1">Zone: <span class="text-cyan-400">{{ colis.zone?.nom }}</span></p>
                    <p *ngIf="colis.livreur" class="text-slate-500 text-xs mt-1">Agent: <span class="text-white font-bold">{{ colis.livreur.prenom }} {{ colis.livreur.nom }}</span></p>
                    <p *ngIf="!colis.livreur" class="text-yellow-500/70 text-xs mt-1 italic">Unassigned</p>
                </div>

                <div class="flex items-center justify-between pt-4 border-t border-white/5">
                     <span [ngClass]="getPrioriteClass(colis.prioriteStatus)" class="text-xs font-bold flex items-center gap-2">
                        <span class="w-2 h-2 rounded-full" [ngClass]="{'bg-red-500': colis.prioriteStatus === 'URGENT', 'bg-blue-500': colis.prioriteStatus === 'NORMAL'}"></span>
                        {{ colis.prioriteStatus }}
                    </span>
                    <div class="flex items-center gap-3">
                        <button (click)="$event.stopPropagation(); trackColis(colis)" class="text-xs font-bold text-cyan-400 hover:text-white transition-colors">Track</button>
                        <span class="text-xs text-slate-500">{{ colis.dateCreation | date:'shortDate' }}</span>
                    </div>
                </div>
            </div>
        </div>

        <!-- Empty State -->
        <div *ngIf="!isLoading && colisList.length === 0" class="col-span-full text-center py-20 text-slate-500">
            No active shipments found requiring attention.
        </div>
    </div>

    <!-- PERSONNEL VIEW -->
    <div *ngIf="activeTab === 'personnel'" class="z-10 relative">
        
        <div class="flex justify-end mb-6">
            <button (click)="openLivreurModal()" class="bg-cyan-600 hover:bg-cyan-500 text-white px-6 py-2 rounded-lg font-bold text-sm transition-colors flex items-center gap-2">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
                Add New Agent
            </button>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
             <!-- Loading State -->
            <div *ngIf="isLoading" class="col-span-full flex justify-center py-20">
                <div class="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-cyan-500"></div>
            </div>

            <!-- Livreur Card -->
            <div *ngFor="let livreur of livreurList" class="bg-[#0f172a] border border-white/5 rounded-2xl p-6 relative group hover:border-cyan-500/30 transition-all">
                 <div class="flex items-start justify-between mb-4">
                     <div class="w-12 h-12 rounded-full bg-cyan-500/10 flex items-center justify-center text-cyan-400 font-bold text-lg">
                        {{ livreur.prenom.charAt(0) }}{{ livreur.nom.charAt(0) }}
                     </div>
                     <button (click)="deleteLivreur(livreur.id)" class="text-slate-600 hover:text-red-500 transition-colors p-2">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                     </button>
                 </div>
                 
                 <h3 class="text-white font-bold text-lg">{{ livreur.prenom }} {{ livreur.nom }}</h3>
                 <p class="text-slate-400 text-xs mb-4">{{ livreur.email }}</p>
                 
                 <div class="space-y-2 pt-4 border-t border-white/5 text-sm">
                    <div class="flex justify-between">
                        <span class="text-slate-500">Phone</span>
                        <span class="text-white">{{ livreur.telephone }}</span>
                    </div>
                    <div class="flex justify-between">
                        <span class="text-slate-500">Vehicle</span>
                        <span class="text-white">{{ livreur.vehicule || 'N/A' }}</span>
                    </div>
                    <div class="flex justify-between">
                        <span class="text-slate-500">Zone</span>
                        <span class="text-cyan-400 font-mono">{{ livreur.zoneAssignee?.nom || 'Unassigned' }}</span>
                    </div>
                 </div>
            </div>
            
            <!-- Empty State -->
            <div *ngIf="!isLoading && livreurList.length === 0" class="col-span-full text-center py-20 text-slate-500">
                No delivery agents found. Create one to get started.
            </div>
        </div>
    </div>


    <!-- Assignment Panel (Already implemented, kept same) -->
    <div *ngIf="selectedColis" class="fixed inset-0 z-50 flex justify-end bg-black/50 backdrop-blur-sm" (click)="closePanel()">
        <!-- ... existing content ... -->
        <div class="w-full max-w-lg bg-[#050b14] h-full shadow-2xl border-l border-white/10 p-8 flex flex-col no-click" (click)="$event.stopPropagation()">
            <!-- ... -->
             <div class="flex justify-between items-center mb-8 border-b border-white/10 pb-6">
                 <div>
                    <h2 class="text-2xl font-bold text-white">Assign Livreur</h2>
                    <p class="text-slate-400 text-sm mt-1">Select an agent for Shipment #{{ selectedColis.id.substring(0,8) }}</p>
                 </div>
                 <button (click)="closePanel()" class="w-8 h-8 rounded-full bg-white/5 hover:bg-white/10 flex items-center justify-center transition">
                    <svg class="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
                 </button>
            </div>

            <h3 class="text-slate-400 text-xs uppercase tracking-widest font-bold mb-4">Eligible Agents (Zone Match)</h3>
            
            <div class="space-y-3 overflow-y-auto flex-1 pr-2">
                 <div *ngIf="isAssignmentLoading" class="flex justify-center py-10">
                    <div class="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-cyan-500"></div>
                 </div>

                 <div *ngIf="!isAssignmentLoading && eligibleLivreurs.length === 0" class="text-center py-10 text-slate-500 border border-dashed border-white/10 rounded-xl">
                    No eligible livreurs found in this zone.
                 </div>

                 <div *ngFor="let livreur of eligibleLivreurs" class="flex items-center justify-between p-4 bg-[#0f172a] border border-white/5 rounded-xl hover:border-cyan-500/30 transition-all group">
                    <div class="flex items-center gap-4">
                        <div class="w-10 h-10 rounded-full bg-cyan-500/10 text-cyan-500 flex items-center justify-center font-bold">
                            {{ livreur.prenom.charAt(0) }}{{ livreur.nom.charAt(0) }}
                        </div>
                        <div>
                            <h4 class="text-white font-bold text-sm">{{ livreur.prenom }} {{ livreur.nom }}</h4>
                            <p class="text-slate-500 text-xs flex items-center gap-2">
                                <span class="w-1.5 h-1.5 rounded-full bg-green-500"></span>
                                Available
                            </p>
                        </div>
                    </div>
                    <button (click)="assignLivreur(livreur.id)" class="bg-white text-black text-xs font-bold px-4 py-2 rounded-lg hover:bg-cyan-400 transition-colors">
                        ASSIGN
                    </button>
                 </div>
            </div>
        </div>
    </div>

    <!-- Tracking Modal -->
    <div *ngIf="isTrackingModalOpen" class="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4" (click)="closeTrackingModal()">
        <div class="bg-[#0f172a] border border-white/10 rounded-2xl w-full max-w-md max-h-[80vh] overflow-y-auto no-click relative" (click)="$event.stopPropagation()">
            <div class="p-6 border-b border-white/10 flex justify-between items-center sticky top-0 bg-[#0f172a] z-10">
                <h2 class="text-xl font-bold text-white">Tracking History</h2>
                <button (click)="closeTrackingModal()" class="text-slate-400 hover:text-white">
                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
                </button>
            </div>
            
            <div class="p-6">
                <div *ngIf="trackingHistory.length === 0" class="text-center py-8 text-slate-500">
                    No history events found.
                </div>

                <div class="relative border-l border-white/10 ml-3 space-y-8">
                    <div *ngFor="let event of trackingHistory" class="relative pl-8">
                         <div class="absolute -left-1.5 top-1.5 w-3 h-3 rounded-full bg-cyan-500 border border-[#0f172a]"></div>
                         <p class="text-white font-bold text-sm">{{ event.status }}</p>
                         <p class="text-slate-400 text-xs mt-1">{{ event.commentaire || 'Status updated' }}</p>
                         <p class="text-slate-600 text-[10px] mt-1">{{ event.dateChangement | date:'medium' }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Create Livreur Modal -->
    <div *ngIf="isLivreurModalOpen" class="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4" (click)="closeLivreurModal()">
        <div class="bg-[#0f172a] border border-white/10 rounded-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto no-click shadow-2xl" (click)="$event.stopPropagation()">
            <div class="p-8">
                <div class="flex justify-between items-center mb-6">
                    <h2 class="text-2xl font-bold text-white">Register New Agent</h2>
                    <button (click)="closeLivreurModal()" class="text-slate-400 hover:text-white">
                        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
                    </button>
                </div>

                <form [formGroup]="livreurForm" (ngSubmit)="submitLivreur()" class="space-y-4">
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <label class="block text-slate-400 text-xs font-bold uppercase mb-2">First Name</label>
                            <input formControlName="prenom" type="text" class="w-full bg-black/20 border border-white/10 rounded-lg px-4 py-3 text-white focus:border-cyan-500 focus:outline-none transition-colors">
                        </div>
                        <div>
                            <label class="block text-slate-400 text-xs font-bold uppercase mb-2">Last Name</label>
                            <input formControlName="nom" type="text" class="w-full bg-black/20 border border-white/10 rounded-lg px-4 py-3 text-white focus:border-cyan-500 focus:outline-none transition-colors">
                        </div>
                    </div>

                    <div>
                        <label class="block text-slate-400 text-xs font-bold uppercase mb-2">Email</label>
                        <input formControlName="email" type="email" class="w-full bg-black/20 border border-white/10 rounded-lg px-4 py-3 text-white focus:border-cyan-500 focus:outline-none transition-colors">
                    </div>

                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <label class="block text-slate-400 text-xs font-bold uppercase mb-2">Phone</label>
                            <input formControlName="telephone" type="tel" class="w-full bg-black/20 border border-white/10 rounded-lg px-4 py-3 text-white focus:border-cyan-500 focus:outline-none transition-colors">
                        </div>
                        <div>
                            <label class="block text-slate-400 text-xs font-bold uppercase mb-2">Vehicle</label>
                            <input formControlName="vehicule" type="text" placeholder="e.g. Van, Bike" class="w-full bg-black/20 border border-white/10 rounded-lg px-4 py-3 text-white focus:border-cyan-500 focus:outline-none transition-colors">
                        </div>
                    </div>

                    <div>
                        <label class="block text-slate-400 text-xs font-bold uppercase mb-2">Assigned Zone</label>
                        <select formControlName="zoneAssigneeId" class="w-full bg-black/20 border border-white/10 rounded-lg px-4 py-3 text-white focus:border-cyan-500 focus:outline-none transition-colors">
                            <option value="" disabled selected>Select a Zone</option>
                            <option *ngFor="let zone of zoneList" [value]="zone.id">{{ zone.nom }} - {{ zone.codePostal }}</option>
                        </select>
                        <p class="text-xs text-slate-500 mt-1">Agent will operate primarily in this zone.</p>
                    </div>

                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <label class="block text-slate-400 text-xs font-bold uppercase mb-2">Password</label>
                            <input formControlName="password" type="password" class="w-full bg-black/20 border border-white/10 rounded-lg px-4 py-3 text-white focus:border-cyan-500 focus:outline-none transition-colors">
                        </div>
                        <div>
                            <label class="block text-slate-400 text-xs font-bold uppercase mb-2">Confirm Password</label>
                            <input formControlName="confirmPassword" type="password" class="w-full bg-black/20 border border-white/10 rounded-lg px-4 py-3 text-white focus:border-cyan-500 focus:outline-none transition-colors">
                        </div>
                    </div>

                    <div class="pt-6 border-t border-white/10 flex justify-end gap-3">
                        <button type="button" (click)="closeLivreurModal()" class="px-6 py-2 rounded-lg text-slate-400 hover:bg-white/5 transition-colors font-bold">Cancel</button>
                        <button type="submit" [disabled]="livreurForm.invalid || isLivreurActionLoading" class="px-6 py-2 rounded-lg bg-cyan-600 hover:bg-cyan-500 text-white font-bold transition-colors disabled:opacity-50">
                            {{ isLivreurActionLoading ? 'Creating...' : 'Create Agent' }}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>

// SmartlogiV2_FrontReactTs/src/features/dashboard/pages/ManagerDashboard.tsx
import React, { useState, useEffect } from 'react';
import { useAppDispatch, useAppSelector } from '../../../store/hooks';
import { selectUser, logout } from '../../auth/authSlice';
import { useNavigate } from 'react-router-dom';
import UserProfile from '../../users/components/UserProfile';
import { 
    fetchDashboardStats, 
    fetchColis, 
    fetchLivreurs, 
    fetchEligibleLivreurs, 
    assignLivreur, 
    createLivreur, 
    deleteLivreur, 
    resetEligible,
    fetchZones
} from '../managerSlice';
import { type Colis } from '../../parcels/colisSlice';
import { type Livreur } from '../managerService';

const ManagerDashboard = () => {
    const dispatch = useAppDispatch();
    const navigate = useNavigate();
    const user = useAppSelector(selectUser);
    
    
    const { stats, colis, livreurs, eligibleLivreurs, eligibleState, zones } = useAppSelector(state => state.manager);

    
    const [activeTab, setActiveTab] = useState<'SHIPMENTS' | 'DRIVERS' | 'PROFILE'>('SHIPMENTS');
    const [shipmentFilter, setShipmentFilter] = useState<'ALL' | 'AVAILABLE' | 'ASSIGNED'>('ALL');
    const [page, setPage] = useState(0);

    
    const [selectedColis, setSelectedColis] = useState<Colis | null>(null);
    const [isAssignModalOpen, setIsAssignModalOpen] = useState(false);
    const [selectedLivreurId, setSelectedLivreurId] = useState('');

    const [isDriverModalOpen, setIsDriverModalOpen] = useState(false);
    const [newDriver, setNewDriver] = useState({
        nom: '', prenom: '', email: '', telephone: '', password: '', confirmPassword: '', vehicule: 'SCOOTER', zoneAssigneeId: '' 
    });

    
    useEffect(() => {
        dispatch(fetchDashboardStats());
        dispatch(fetchZones());
    }, [dispatch]);

    
    useEffect(() => {
        if (activeTab === 'SHIPMENTS') {
            dispatch(fetchColis({ page, size: 10, filter: shipmentFilter }));
        } else if (activeTab === 'DRIVERS') {
            dispatch(fetchLivreurs({ page, size: 10 }));
        }
    }, [dispatch, activeTab, shipmentFilter, page]);


    const handleLogout = () => {
        dispatch(logout());
        navigate('/staff-login');
    };

    

    const openAssignModal = (colis: Colis) => {
        setSelectedColis(colis);
        dispatch(resetEligible());
        dispatch(fetchEligibleLivreurs(colis.id));
        setIsAssignModalOpen(true);
    };

    const handleAssign = async () => {
        if (selectedColis && selectedLivreurId) {
            await dispatch(assignLivreur({ colisId: selectedColis.id, livreurId: selectedLivreurId }));
            setIsAssignModalOpen(false);
            setSelectedLivreurId('');
            setSelectedColis(null);
            
            dispatch(fetchColis({ page, size: 10, filter: shipmentFilter }));
        }
    };

    const handleCreateDriver = async (e: React.FormEvent) => {
        e.preventDefault();
        
        if (newDriver.password !== newDriver.confirmPassword) {
            alert("Passwords do not match");
            return;
        }
        
        
        
        
        await dispatch(createLivreur({
            ...newDriver,
            zoneAssignee: { id: newDriver.zoneAssigneeId } 
             
        }));
        setNewDriver({ nom: '', prenom: '', email: '', telephone: '', password: '', confirmPassword: '', vehicule: 'SCOOTER', zoneAssigneeId: '' });
        setIsDriverModalOpen(false);
    };

    const handleDeleteDriver = async (id: string) => {
        if (window.confirm('Delete this driver?')) {
            await dispatch(deleteLivreur(id));
        }
    };
    
    
    

    return (
        <div className="min-h-screen bg-stone-50 text-slate-900 font-sans selection:bg-orange-200 selection:text-orange-900">
            {}
            <nav className="sticky top-0 z-50 bg-white/80 backdrop-blur-md border-b border-stone-200">
                <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
                    {}
                    <div className="flex items-center gap-3">
                         <div className="w-10 h-10 bg-orange-600 rounded-xl flex items-center justify-center font-black text-xl shadow-lg shadow-orange-500/20 text-white">M</div>
                         <div className="leading-tight">
                            <span className="block font-bold text-lg tracking-tight text-slate-900">SmartLogi<span className="text-orange-600">Manager</span></span>
                            <span className="text-xs text-slate-500 font-medium tracking-wide">OPERATIONS CENTER</span>
                         </div>
                    </div>

                    {}
                    <div className="hidden md:flex bg-stone-100 p-1.5 rounded-xl border border-stone-200">
                        <button onClick={() => setActiveTab('SHIPMENTS')} className={`px-5 py-2 rounded-lg text-sm font-bold transition-all ${activeTab === 'SHIPMENTS' ? 'bg-white text-orange-600 shadow-sm' : 'text-slate-500 hover:text-slate-900 hover:bg-stone-200'}`}>
                            📦 Colis
                        </button>
                        <button onClick={() => setActiveTab('DRIVERS')} className={`px-5 py-2 rounded-lg text-sm font-bold transition-all ${activeTab === 'DRIVERS' ? 'bg-white text-orange-600 shadow-sm' : 'text-slate-500 hover:text-slate-900 hover:bg-stone-200'}`}>
                            🚚 Livreurs
                        </button>
                        <button onClick={() => setActiveTab('PROFILE')} className={`px-5 py-2 rounded-lg text-sm font-bold transition-all ${activeTab === 'PROFILE' ? 'bg-white text-orange-600 shadow-sm' : 'text-slate-500 hover:text-slate-900 hover:bg-stone-200'}`}>
                            👤 Profil
                        </button>
                    </div>

                    {}
                    <div className="flex items-center gap-4">
                        <div className="text-right hidden md:block">
                            <div className="text-sm font-bold text-slate-900">{user?.prenom} {user?.nom}</div>
                            <div className="text-[10px] uppercase tracking-widest text-orange-600 font-bold bg-orange-50 px-2 py-0.5 rounded-full border border-orange-100">Manager</div>
                        </div>
                        <div className="w-10 h-10 rounded-full bg-slate-900 text-white border-2 border-white shadow-md flex items-center justify-center font-bold">
                            {user?.prenom?.charAt(0)}
                        </div>
                    </div>
                </div>
            </nav>

            {}
            <main className="max-w-7xl mx-auto px-6 py-8">
                
                {}
                {stats && (
                    <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8 animate-fadeIn">
                        <div className="p-6 bg-white rounded-2xl border border-stone-100 shadow-sm hover:shadow-md transition-shadow">
                            <h3 className="text-slate-400 text-xs uppercase font-bold tracking-wider mb-2">Total Colis</h3>
                            <div className="flex items-baseline gap-2">
                                <p className="text-3xl font-black text-slate-900">{stats.TOTAL}</p>
                                <span className="text-xs font-bold text-green-500 bg-green-50 px-2 py-1 rounded-full">+12%</span>
                            </div>
                        </div>
                        <div className="p-6 bg-white rounded-2xl border border-stone-100 shadow-sm hover:shadow-md transition-shadow">
                            <h3 className="text-slate-400 text-xs uppercase font-bold tracking-wider mb-2">En Attente</h3>
                            <div className="flex items-baseline gap-2">
                                <p className="text-3xl font-black text-orange-500">{stats.CREE + stats.COLLECTE}</p>
                                <span className="text-xs text-slate-400">Action Requise</span>
                            </div>
                        </div>
                        <div className="p-6 bg-white rounded-2xl border border-stone-100 shadow-sm hover:shadow-md transition-shadow">
                             <h3 className="text-slate-400 text-xs uppercase font-bold tracking-wider mb-2">En Transit</h3>
                             <p className="text-3xl font-black text-blue-500">{stats.EN_TRANSIT}</p>
                        </div>
                        <div className="p-6 bg-white rounded-2xl border border-stone-100 shadow-sm hover:shadow-md transition-shadow">
                             <h3 className="text-slate-400 text-xs uppercase font-bold tracking-wider mb-2">Livrés</h3>
                             <p className="text-3xl font-black text-slate-900">{stats.LIVRE}</p>
                        </div>
                    </div>
                )}

                {}
                {activeTab === 'SHIPMENTS' && (
                    <div className="space-y-6 animate-fadeIn">
                        {}
                        <div className="flex gap-4 border-b border-stone-200 pb-2">
                             {(['ALL', 'AVAILABLE', 'ASSIGNED'] as const).map(f => (
                                 <button
                                    key={f}
                                    onClick={() => { setShipmentFilter(f); setPage(0); }}
                                    className={`pb-2 px-1 text-sm font-bold transition-all border-b-2 ${shipmentFilter === f ? 'border-orange-500 text-orange-600' : 'border-transparent text-slate-500 hover:text-slate-800'}`}
                                 >
                                    {f === 'ALL' ? 'Tous les Colis' : f === 'AVAILABLE' ? 'Non Assignés' : 'Assignés / En cours'}
                                 </button>
                             ))}
                        </div>

                        {}
                        <div className="bg-white border border-stone-200 rounded-2xl shadow-sm overflow-hidden">
                            <table className="w-full text-left">
                                <thead className="bg-stone-50 border-b border-stone-100 text-xs font-bold text-slate-500 uppercase tracking-wider">
                                    <tr>
                                        <th className="px-6 py-4">ID Colis</th>
                                        <th className="px-6 py-4">Statut</th>
                                        <th className="px-6 py-4">Destination</th>
                                        <th className="px-6 py-4">Priorité</th>
                                        <th className="px-6 py-4 text-right">Action</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-stone-100">
                                    {colis.data.map(c => (
                                        <tr key={c.id} className="hover:bg-stone-50 transition-colors">
                                            <td className="px-6 py-4">
                                                <div className="font-bold text-slate-900">#{c.id.substring(0, 8)}</div>
                                                <div className="text-xs text-slate-400">{c.dateCreation}</div>
                                            </td>
                                            <td className="px-6 py-4">
                                                <span className={`px-3 py-1 rounded-full text-xs font-bold border ${getStatusClass(c.statut)}`}>
                                                    {c.statut}
                                                </span>
                                            </td>
                                            <td className="px-6 py-4">
                                                <div className="font-bold text-slate-800">{c.villeDestination}</div>
                                                <div className="text-xs text-slate-400">{c.codePostal}</div>
                                            </td>
                                            <td className="px-6 py-4">
                                                <span className={`font-bold text-xs ${getPriorityClass(c.priorite)}`}>{c.priorite}</span>
                                            </td>
                                            <td className="px-6 py-4 text-right">
                                                {c.statut === 'CREE' && (
                                                    <button 
                                                        onClick={() => openAssignModal(c)}
                                                        className="bg-slate-900 hover:bg-orange-600 text-white px-4 py-2 rounded-lg text-xs font-bold transition-all shadow-md shadow-slate-900/10"
                                                    >
                                                        Assigner
                                                    </button>
                                                )}
                                                {c.statut !== 'CREE' && (
                                                     <span className="text-xs font-bold text-slate-400 bg-slate-100 px-3 py-1.5 rounded-lg">Géré</span>
                                                )}
                                            </td>
                                        </tr>
                                    ))}
                                    {colis.data.length === 0 && (
                                        <tr><td colSpan={5} className="px-6 py-12 text-center text-slate-400 font-medium">Aucun colis trouvé.</td></tr>
                                    )}
                                </tbody>
                            </table>
                        </div>
                    </div>
                )}

                {activeTab === 'DRIVERS' && (
                    <div className="space-y-6 animate-fadeIn">
                        <div className="flex justify-between items-center">
                            <h2 className="text-xl font-bold text-slate-900">Gestion des Livreurs</h2>
                            <button 
                                onClick={() => setIsDriverModalOpen(true)}
                                className="bg-orange-600 hover:bg-orange-500 text-white px-5 py-2.5 rounded-xl font-bold text-sm shadow-lg shadow-orange-500/20 transition-all flex items-center gap-2"
                            >
                                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
                                Nouveau Livreur
                            </button>
                        </div>
                         
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                            {livreurs.data.map(driver => (
                                <div key={driver.id} className="bg-white p-6 rounded-2xl border border-stone-200 shadow-sm hover:border-orange-200 hover:shadow-orange-500/5 transition-all group">
                                    <div className="flex justify-between items-start mb-4">
                                        <div className="w-12 h-12 rounded-xl bg-slate-900 text-white flex items-center justify-center font-bold text-lg">
                                            {driver.nom.charAt(0)}{driver.prenom.charAt(0)}
                                        </div>
                                        <div className={`px-3 py-1 rounded-lg text-xs font-bold ${driver.status === 'DISPONIBLE' ? 'bg-green-100 text-green-700' : 'bg-red-50 text-red-600'}`}>
                                            {driver.status}
                                        </div>
                                    </div>
                                    <h3 className="font-bold text-lg text-slate-900">{driver.prenom} {driver.nom}</h3>
                                    <div className="text-slate-500 text-sm mb-4">{driver.email}</div>
                                    
                                    <div className="space-y-2 text-sm border-t border-stone-100 pt-4">
                                        <div className="flex justify-between">
                                            <span className="text-slate-400">Zone</span>
                                            <span className="font-bold text-slate-700">{driver.zoneAssignee?.nom || 'N/A'}</span>
                                        </div>
                                        <div className="flex justify-between">
                                            <span className="text-slate-400">Véhicule</span>
                                            <span className="font-bold text-slate-700">{driver.vehicule}</span>
                                        </div>
                                    </div>
                                    
                                     <button 
                                        onClick={() => handleDeleteDriver(driver.id)}
                                        className="w-full mt-4 py-2 text-slate-400 hover:text-red-500 hover:bg-red-50 rounded-lg text-sm font-bold transition-all border border-transparent hover:border-red-100"
                                     >
                                         Supprimer
                                     </button>
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                 {activeTab === 'PROFILE' && (
                    <div className="animate-fadeIn">
                         <UserProfile user={user} onLogout={handleLogout} />
                    </div>
                )}
            </main>

            {}
            {isAssignModalOpen && selectedColis && (
               <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4 animate-fadeIn" onClick={() => setIsAssignModalOpen(false)}>
                    <div className="bg-white rounded-2xl w-full max-w-lg shadow-2xl overflow-hidden" onClick={e => e.stopPropagation()}>
                        <div className="p-6 border-b border-stone-100 bg-stone-50 flex justify-between items-center">
                            <h3 className="text-lg font-bold text-slate-900">Assigner un Livreur</h3>
                            <button onClick={() => setIsAssignModalOpen(false)} className="text-slate-400 hover:text-red-500"><svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"></path></svg></button>
                        </div>
                        <div className="p-6">
                            <div className="mb-6">
                                <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Sélectionner un Livreur</label>
                                {eligibleState.loading ? (
                                    <div className="text-orange-500 font-bold animate-pulse">Vérification de la disponibilité...</div>
                                ) : eligibleLivreurs.length > 0 ? (
                                    <select 
                                        className="w-full bg-stone-50 border border-stone-200 rounded-xl px-4 py-3 font-bold text-slate-700 focus:outline-none focus:border-orange-500"
                                        value={selectedLivreurId}
                                        onChange={e => setSelectedLivreurId(e.target.value)}
                                    >
                                        <option value="">-- Choisir un livreur --</option>
                                        {eligibleLivreurs.map(l => (
                                            <option key={l.id} value={l.id}>{l.prenom} {l.nom} ({l.status})</option>
                                        ))}
                                    </select>
                                ) : (
                                    <div className="p-4 bg-red-50 text-red-600 rounded-xl text-sm font-bold border border-red-100">
                                        Aucun livreur disponible dans la zone 
                                        <span className="text-red-800 mx-1">{selectedColis.statut === 'CREE' ? (selectedColis.zoneOrigine?.nom || selectedColis.codePostalOrigine) : selectedColis.zone?.nom}</span>.
                                        Veuillez assigner un livreur à cette zone.
                                    </div>
                                )}
                            </div>
                            <div className="flex justify-end gap-3">
                                <button onClick={() => setIsAssignModalOpen(false)} className="px-5 py-2.5 text-slate-500 font-bold hover:bg-stone-100 rounded-xl transition">Annuler</button>
                                <button 
                                    disabled={!selectedLivreurId} 
                                    onClick={handleAssign}
                                    className="px-6 py-2.5 bg-orange-600 text-white font-bold rounded-xl shadow-lg shadow-orange-500/30 disabled:opacity-50 hover:bg-orange-500 transition"
                                >
                                    Confirmer
                                </button>
                            </div>
                        </div>
                    </div>
               </div> 
            )}

            {}
            {isDriverModalOpen && (
                <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4 animate-fadeIn" onClick={() => setIsDriverModalOpen(false)}>
                    <div className="bg-white rounded-2xl w-full max-w-lg shadow-2xl overflow-hidden max-h-[90vh] overflow-y-auto custom-scrollbar" onClick={e => e.stopPropagation()}>
                         <div className="p-6 border-b border-stone-100 bg-stone-50">
                            <h3 className="text-xl font-bold text-slate-900">Ajouter un Livreur</h3>
                            <p className="text-sm text-slate-500">Créer un compte pour le personnel de livraison</p>
                        </div>
                        <form onSubmit={handleCreateDriver} className="p-6 space-y-4">
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-xs font-bold text-slate-500 mb-1">Prénom</label>
                                    <input required type="text" className="w-full bg-stone-50 border border-stone-200 rounded-xl px-4 py-2.5 focus:border-orange-500 focus:outline-none" 
                                           value={newDriver.prenom} onChange={e => setNewDriver({...newDriver, prenom: e.target.value})} />
                                </div>
                                <div>
                                    <label className="block text-xs font-bold text-slate-500 mb-1">Nom</label>
                                    <input required type="text" className="w-full bg-stone-50 border border-stone-200 rounded-xl px-4 py-2.5 focus:border-orange-500 focus:outline-none" 
                                           value={newDriver.nom} onChange={e => setNewDriver({...newDriver, nom: e.target.value})} />
                                </div>
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-slate-500 mb-1">Email</label>
                                <input required type="email" className="w-full bg-stone-50 border border-stone-200 rounded-xl px-4 py-2.5 focus:border-orange-500 focus:outline-none" 
                                       value={newDriver.email} onChange={e => setNewDriver({...newDriver, email: e.target.value})} />
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-slate-500 mb-1">Téléphone</label>
                                <input required type="tel" className="w-full bg-stone-50 border border-stone-200 rounded-xl px-4 py-2.5 focus:border-orange-500 focus:outline-none" 
                                       value={newDriver.telephone} onChange={e => setNewDriver({...newDriver, telephone: e.target.value})} />
                            </div>
                             <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-xs font-bold text-slate-500 mb-1">Mot de passe</label>
                                    <input required type="password" className="w-full bg-stone-50 border border-stone-200 rounded-xl px-4 py-2.5 focus:border-orange-500 focus:outline-none" 
                                           value={newDriver.password} onChange={e => setNewDriver({...newDriver, password: e.target.value})} />
                                </div>
                                <div>
                                    <label className="block text-xs font-bold text-slate-500 mb-1">Confirmer</label>
                                    <input required type="password" className="w-full bg-stone-50 border border-stone-200 rounded-xl px-4 py-2.5 focus:border-orange-500 focus:outline-none" 
                                           value={newDriver.confirmPassword} onChange={e => setNewDriver({...newDriver, confirmPassword: e.target.value})} />
                                </div>
                            </div>
                             <div>
                                <label className="block text-xs font-bold text-slate-500 mb-1">Type de Véhicule</label>
                                <select className="w-full bg-stone-50 border border-stone-200 rounded-xl px-4 py-2.5 focus:border-orange-500 focus:outline-none"
                                        value={newDriver.vehicule} onChange={e => setNewDriver({...newDriver, vehicule: e.target.value as any})}>
                                    <option value="SCOOTER">Scooter</option>
                                    <option value="VOITURE">Voiture</option>
                                    <option value="CAMION">Camion</option>
                                    <option value="VELO">Vélo</option>
                                </select>
                            </div>
                            {}
                             <div>
                                <label className="block text-xs font-bold text-slate-500 mb-1">Zone Assignée</label>
                                {zones && zones.length > 0 ? (
                                    <select 
                                        required 
                                        className="w-full bg-stone-50 border border-stone-200 rounded-xl px-4 py-2.5 focus:border-orange-500 focus:outline-none"
                                        value={newDriver.zoneAssigneeId} 
                                        onChange={e => setNewDriver({...newDriver, zoneAssigneeId: e.target.value})}
                                    >
                                        <option value="">-- Sélectionner une zone --</option>
                                        {zones.map(zone => (
                                            <option key={zone.id} value={zone.id}>
                                                {zone.nom} ({zone.ville})
                                            </option>
                                        ))}
                                    </select>
                                ) : (
                                    <div className="text-red-500 text-xs italic p-2 border border-red-100 bg-red-50 rounded-lg">
                                        Aucune zone disponible. Veuillez en créer une d'abord via l'API ou demandez à un Admin.
                                    </div>
                                )}
                            </div>

                            <div className="flex justify-end gap-3 pt-4">
                                <button type="button" onClick={() => setIsDriverModalOpen(false)} className="px-5 py-2.5 text-slate-500 font-bold hover:bg-stone-100 rounded-xl transition">Annuler</button>
                                <button type="submit" className="px-6 py-2.5 bg-orange-600 text-white font-bold rounded-xl shadow-lg shadow-orange-500/30 hover:bg-orange-500 transition">Créer Livreur</button>
                            </div>
                        </form>
                    </div>
                </div>
            )}

        </div>
    );
};


const getPriorityClass = (priorite: string): string => {
    switch (priorite) {
        case 'URGENT': return 'text-red-500';
        case 'NORMAL': return 'text-blue-500';
        default: return 'text-slate-500';
    }
}

const getStatusClass = (status: string): string => {
    switch (status) {
        case 'CREE': return 'bg-yellow-50 text-yellow-600 border-yellow-200';
        case 'COLLECTE': return 'bg-blue-50 text-blue-600 border-blue-200';
        case 'EN_TRANSIT': return 'bg-purple-50 text-purple-600 border-purple-200';
        case 'LIVRE': return 'bg-green-50 text-green-600 border-green-200';
        case 'ANNULE': return 'bg-red-50 text-red-600 border-red-200';
        default: return 'bg-slate-50 text-slate-600 border-slate-200';
    }
}

export default ManagerDashboard;
